;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: OneWire_DSINT.asm
;;   Version: 1.1, Updated on 2015/3/4 at 22:26:45
;;  Generated by PSoC Designer 5.4.3191
;;
;;  DESCRIPTION: OneWire Interrupt Service Routine
;;
;;-----------------------------------------------------------------------------
;;   Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "OneWire_DS.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _OneWire_DS_ISR

AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _OneWire_DS_ISR
;
;  DESCRIPTION: With ParasitePower enabled this ISR sets TX pin to strong
;               drive mode immediately after transmission of last data bit.
;-----------------------------------------------------------------------------

_OneWire_DS_ISR:
IF (OneWire_DS_PARASITE_ENABLE)
    M8C_SetBank1
    and   REG[OneWire_DS_OUT_PORT_DM1],~OneWire_DS_OUT_PORT_MASK
    M8C_SetBank0
ENDIF
   reti

; end of file OneWire_DSINT.asm
