;  Generated by PSoC Designer 5.4.3191
;
; =============================================================================
; FILENAME: PSoCConfigTBL.asm
;  
; Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;  
; NOTES:
; Do not modify this file. It is generated by PSoC Designer each time the
; generate application function is run. The values of the parameters in this
; file can be modified by changing the values of the global parameters in the
; device editor.
;  
; =============================================================================
 
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_jp_exercice3_Bank1
export LoadConfigTBL_jp_exercice3_Bank0
export LoadConfigTBL_jp_exercice3_Ordered
AREA lit(rom, rel)
LoadConfigTBL_jp_exercice3_Bank0:
;  Instance name I2CM, User Module I2Cm
;  Instance name LCD, User Module LCD
;  Instance name OneWire_DS, User Module OneWire
;       Instance name OneWire_DS, Block Name BitClk(DBB01)
	db		27h, 00h		;OneWire_DS_BITCLK_CONTROL_REG(DBB01CR0)
	db		25h, 00h		;OneWire_DS_BITCLK_PERIOD_REG (DBB01DR1)
	db		26h, 00h		;OneWire_DS_BITCLK_COMPARE_REG(DBB01DR2)
;       Instance name OneWire_DS, Block Name XCVR(DCB02)
	db		2bh, 00h		;OneWire_DS_XCVR_CONTROL_REG(DCB02CR0)
	db		29h, 00h		;OneWire_DS_XCVR_TX_BUFFER_REG(DCB02DR1)
	db		2ah, 00h		;OneWire_DS_XCVR_RX_BUFFER_REG(DCB02DR2)
;  Instance name SHADOW_P1, User Module SHADOWREGS
;  Instance name SPIM, User Module SPIM
;       Instance name SPIM, Block Name SPIM(DCB03)
	db		2fh, 00h		;SPIM_CONTROL_REG  (DCB03CR0)
	db		2dh, 00h		;SPIM_TX_BUFFER_REG(DCB03DR1)
	db		2eh, 00h		;SPIM_RX_BUFFER_REG(DCB03DR2)
;  Instance name SleepTimer, User Module SleepTimer
;  Instance name UART, User Module UART
;       Instance name UART, Block Name RX(DCB13)
	db		3fh, 00h		;UART_RX_CONTROL_REG(DCB13CR0)
	db		3dh, 00h		;UART_(DCB13DR1)
	db		3eh, 00h		;UART_RX_BUFFER_REG (DCB13DR2)
;       Instance name UART, Block Name TX(DCB12)
	db		3bh, 00h		;UART_TX_CONTROL_REG(DCB12CR0)
	db		39h, 00h		;UART_TX_BUFFER_REG (DCB12DR1)
	db		3ah, 00h		;UART_(DCB12DR2)
;  Global Register values Bank 0
	db		60h, 28h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 05h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 00h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 00h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2CCFG)
	db		b0h, 8ch		; Row_0_InputMux register (RDI0RI)
	db		b1h, 02h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 88h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		b8h, 55h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 10h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 00h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	db		beh, 04h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	db		ffh
LoadConfigTBL_jp_exercice3_Bank1:
;  Instance name I2CM, User Module I2Cm
;  Instance name LCD, User Module LCD
;  Instance name OneWire_DS, User Module OneWire
;       Instance name OneWire_DS, Block Name BitClk(DBB01)
	db		24h, 21h		;OneWire_DS_BITCLK_FUNC_REG(DBB01FN)
	db		25h, 15h		;OneWire_DS_BITCLK_INPUT_REG(DBB01IN)
	db		26h, 00h		;OneWire_DS_BITCLK_OUTPUT_REG(DBB01OU)
;       Instance name OneWire_DS, Block Name XCVR(DCB02)
	db		28h, 16h		;OneWire_DS_XCVR_FUNC_REG(DCB02FN)
	db		29h, f3h		;OneWire_DS_XCVR_INPUT_REG(DCB02IN)
	db		2ah, 07h		;OneWire_DS_XCVR_OUTPUT_REG(DCB02OU)
;  Instance name SHADOW_P1, User Module SHADOWREGS
;  Instance name SPIM, User Module SPIM
;       Instance name SPIM, Block Name SPIM(DCB03)
	db		2ch, 06h		;SPIM_FUNCTION_REG (DCB03FN)
	db		2dh, d6h		;SPIM_INPUT_REG    (DCB03IN)
	db		2eh, 70h		;SPIM_OUTPUT_REG   (DCB03OU)
;  Instance name SleepTimer, User Module SleepTimer
;  Instance name UART, User Module UART
;       Instance name UART, Block Name RX(DCB13)
	db		3ch, 05h		;UART_RX_FUNC_REG   (DCB13FN)
	db		3dh, 01h		;UART_RX_INPUT_REG  (DCB13IN)
	db		3eh, 40h		;UART_RX_OUTPUT_REG (DCB13OU)
;       Instance name UART, Block Name TX(DCB12)
	db		38h, 0dh		;UART_TX_FUNC_REG   (DCB12FN)
	db		39h, 01h		;UART_TX_INPUT_REG  (DCB12IN)
	db		3ah, 46h		;UART_TX_OUTPUT_REG (DCB12OU)
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 00h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 00h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 7eh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 26h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 01h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_jp_exercice3_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], 01h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], feh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], 3eh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 01h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], 90h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], d4h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], abh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], 83h		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], ech		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], 7fh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 80h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 80h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	mov	reg[0ch], 00h		; Port_3_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	mov	reg[10h], 00h		; Port_4_Data register (PRT4DR)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	mov	reg[14h], 00h		; Port_5_Data register (PRT5DR)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
